bp/task/taskproject/bankapp/urls.py
from . import views
from django.urls import path

app_name='bankapp'


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('userhome/',views.userhome,name='userhome'),
    path('application_form/',views.application_form,name='application_form'),
    path('application_view/',views.application_view,name='application_view'),
    # path('',views.district,name='district'),
    path('ajax/load_branch/',views.load_branch,name='ajax_load_branch'),
    path('message',views.message,name='message'),
    path('logout',views.logout,name='logout'),
]

bp/task/taskproject/taskproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('bankapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                              document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

bp/task/taskproject/bankapp/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.db.models import CASCADE


# Create your models here.
class District(models.Model):
     name = models.CharField(max_length=30)

     def __str__(self):
         return self.name


class Branch(models.Model):
    district = models.ForeignKey(District,on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
         return self.name



class application(models.Model):
    name=models.CharField(max_length=250)
    dob=models.DateField(null=True, blank=True)
    age=models.IntegerField()
    gender=models.CharField(max_length=250)
    phone=models.BigIntegerField()
    email=models.TextField(blank=True)
    address=models.TextField(blank=True)
    district=models.ForeignKey(District,on_delete=models.SET_NULL,blank=True,null=True)
    branch=models.ForeignKey(Branch,on_delete=models.SET_NULL,blank=True,null=True)
    accounttype=models.CharField(max_length=250)
    # materials=models.CharField()

    def __str__(self):
        return self.name

bp/task/taskproject/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from bankapp.models import application, Branch, District
# from .forms import ApplicationForm
import json

app_name='bankapp'


# Create your views here.

def index(request):
    return render(request,"index.html")

# def index(request,):
#     bank=application.objects.all()
#     context={'application_list':bank}
#     return render(request,"index.html",context)
#



def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Already Taken")
                return redirect('/register')
            else:
                user =User.objects.create_user(username=username, password=password)
                user.save();
                return redirect('/login')

                # print("User Account Created")
                # return redirect('login')
        else:
            messages.info(request, "Password is Incorrect")
            return redirect('/register')
        return redirect('/')
    return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/userhome')
        else:
            messages.info(request,"Invalid Credentials")
            return redirect('/login')
    return render(request,"login.html")


def userhome(request):
    return render(request,"userhome.html")

# def userhome(request,id):
#     bank=application.objects.get(id=id)
#     context = {'application_list': bank}
#     return render(request,"application.html",context)

# def application_form(request):
#
#         # return redirect('/application_form')
#
#         if request.method == 'POST':
#             name = request.POST['name']
#             dob = request.POST['dob']
#             age = request.POST['age']
#             gender = request.POST['gender']
#             phone = request.POST['phone']
#             email = request.POST['email']
#             address = request.POST['address']
#             district = request.POST['district']
#             branch = request.POST['branch']
#             accounttype = request.POST['accounttype']
#             app = application(name=name, dob=dob, age=age, gender=gender, phone=phone, email=email, address=address, district=district, branch=branch, accounttype=accounttype)
#             app.save()
#             return redirect('/application_form')

        # d = {'district': district}

        # return redirect('/form_save')
        # return render(request,'application.html',{'districts': districts})
def application_form(request):
    if request.method == 'POST':

        name = request.POST['name']
        #request.session['user_id']=
        dob = request.POST['dob']
        age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        address = request.POST['address']
        # district = request.POST['district']
        # branch = request.POST['branch']
        accounttype = request.POST['accounttype']
        app = application(name=name, dob=dob, age=age, gender=gender, phone=phone, email=email, address=address, accounttype=accounttype)
        app.save();
        messages.info(request, "Application Accepted")
        return redirect('/application_form')
        # return redirect(reverse('/application_view/',kwargs={"application_id": app.pk}))
    districts = District.objects.all()
    return render(request, 'application.html', {'districts': districts})

def application_view(request):
    #id = request.session['user_id']
    current_user = request.user
    id = current_user.id
    print(id)
    bank=application.objects.get(id=id)
    if bank:
       return render(request, 'applicationview.html',{'bank': bank})
    else:
       return render(request, "application.html")


def load_branch(request):
    district_id = request.GET.get('district')
    branch = Branch.objects.filter(district_id=district_id).order_by('name')
    return render(request,'branch_dropdown.html', {'branch':branch})

def logout(request):
    auth.logout(request)
    return redirect('/')

def message(request):
    return render(request,'message.html')

bp/task/taskproject/templates/application1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">


    <title>Application</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-finance-business.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link href="{% static 'register1.css' %}" rel="stylesheet">
</head>
<body style="background-color:green;">

<div class="sub-header" style="height:70px">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-xs-12">
            <ul class="left-info">
              <li><a href="#"><i class="fa fa-clock-o"></i>Mon-Fri 09:00-17:00</a></li>
              <li><a href="#"><i class="fa fa-phone"></i>090-080-0760</a></li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="right-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
<br>

<header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="#"><h2>Bank WebSite</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'bankapp:index' %}">Home
<!--                  <span class="sr-only">(current)</span>-->
                </a>
              </li>
                {% if user.is_authenticated %}
                <li>Welcome {{user.username}}</li>

                <li class="nav-item">
                <a class="nav-link" href="">Logout</a>
                </li>
                {% endif %}



              <li class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Branches
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
<br><br><br><br><br>

<form action="application_form" method="post">
    {% csrf_token %}
    <div class="container">
    <h1>Application Form</h1>

    <hr>

        <label for="name"><b>Name</b></label>
        <input type="text" placeholder="Enter Name" name="name" required><br>

        <label><b>Date Of Birth</b></label>&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="date"  name="dob" required><br>

        <label><b>Age</b></label>
        <input type="text" placeholder="Enter Age"  name="age" required><br>

        <b>Gender</b>&nbsp;&nbsp;&nbsp;&nbsp;
        Male<input type="radio" checked=true name="gender">
        Female<input type="radio"  name="gender"><br><br>

        <label for="phone"><b>Phone Number</b></label><br>
        <input type="text" placeholder="Enter Number" id="phone" name="phone">



        <b>Email Id</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="email" placeholder="Enter Email"  name="email" required><br><br>

        <label for="address"><b>Address</b></label><br>
        <input type="text" placeholder="Enter Address" id="address" name="address" required><br>

        <label for="district"><b>District</b></label>&nbsp;&nbsp;&nbsp;
              <select name="district" id="district">
                <option value="select">Select</option>
                <option value="kottayam">Kottayam</option>
                <option value="idukki">Idukki</option>
                <option value="thiruvananthapuram">Thiruvananthapuram</option>
                <option value="kollam">Kollam</option>
                <option value="palakad">Palakad</option>
                <option value="kozhikode">Kozhikode</option>
                <option value="alapuzha">Alapuzha</option>
                <option value="ernakulam">Ernakulam</option>
                <option value="kannur">Kannur</option>
                <option value="wayanad">Wayanad</option>
                <option value="kasargod">Kasargod</option>
                <option value="malapuram">Malapuram</option>
                <option value="pathanamthitta">Pathanamthitta</option>
                <option value="kollam">Kollam</option>
            </select><br><br>

<!--        <div class="dropdown">-->
<!--            <b>District</b>&nbsp;&nbsp;&nbsp;&nbsp;-->
<!--            <select name="district" id="district">-->
<!--                <option value="select">Select</option>-->
<!--                <option value="kottayam">Kottayam</option>-->
<!--                <option value="idukki">Idukki</option>-->
<!--                <option value="thiruvananthapuram">Thiruvananthapuram</option>-->
<!--                <option value="kollam">Kollam</option>-->
<!--                <option value="palakad">Palakad</option>-->
<!--                <option value="kozhikode">Kozhikode</option>-->
<!--                <option value="alapuzha">Alapuzha</option>-->
<!--                <option value="ernakulam">Ernakulam</option>-->
<!--                <option value="kannur">Kannur</option>-->
<!--                <option value="wayanad">Wayanad</option>-->
<!--                <option value="kasargod">Kasargod</option>-->
<!--                <option value="malapuram">Malapuram</option>-->
<!--                <option value="pathanamthitta">Pathanamthitta</option>-->
<!--                <option value="kollam">Kollam</option>-->
<!--            </select>-->

<!--        </div><br>-->

        <b>Branch</b>
        <input type="text" placeholder="Enter Branch" name="branch">

        <div class="dropdown"><br>
            <b>Account Type   </b>&nbsp;&nbsp;&nbsp;&nbsp;
                <select name="accounttype" id="account">
                    <option value="select">Select</option>
                    <option value="savings">Savings</option>
                    <option value="current">Current</option>
                    <option value="joint">Joint</option>
                    <option value="fixed">Fixed</option>
                </select>

        </div><br>

         <b>Materials</b><br>&nbsp;&nbsp;
            <div>
                <input type="checkbox" id="debit card" name="debitcard">
                    <label for="debit card">Debit Card</label>
            </div>

            <div>
                <input type="checkbox" id="credit card" name="creditcard">
                    <label for="credit card">Credit Card</label>
            </div>

            <div>
                <input type="checkbox" id="cheque book" name="chequebook">
                    <label for="cheque book">Cheque Book</label>
            </div>



            <button type="submit" class="registerbtn">Submit</button>

            <a href="{% url 'bankapp:logout' %}" class="btn btn-danger">Logout</a>


    </div>
</form>



<!--{% for msg in messages %}-->
<!-- <h2>{{msg}}</h2>-->
<!--{% endfor %}-->

<!-- Footer Starts Here -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-3 footer-item">
            <h4>Bank Website</h4>
            <p>We always aim at providing superior, proactive banking service to niche market globally, while providing cost effective and responsive services</p>
            <ul class="social-icons">
              <li><a rel="nofollow" href="https://fb.com/templatemo" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item">
            <h4>Useful Links</h4>
            <ul class="menu-list">
              <li><a href="#">Intrest Rate</a></li>
              <li><a href="#">Service Charge</a></li>
              <li><a href="#">Policies & Guidelines</a></li>
              <li><a href="#">Doorstep banking</a></li>
              <li><a href="#">Smart Banking</a></li>
              <li><a href="#">Safe Banking</a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item">
            <h4>Additional Pages</h4>
            <ul class="menu-list">
              <li><a href="#">About Us</a></li>
              <li><a href="#">How We Work</a></li>
              <li><a href="#">Quick Support</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item last-item">
            <h4>Contact Us</h4>
            <div class="contact-form">
              <form id="contact footer-contact" action="" method="post">
                <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="email" type="text" class="form-control" id="email" pattern="[^ @]*@[^ @]*" placeholder="E-Mail Address" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>Copyright &copy; 2020 Bank Website.

            </p>
          </div>
        </div>
      </div>
    </div>

     <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


</body>
</html>

bp/task/taskproject/templates/branch_dropdown.html
<option value="">---select branch---</option>
{% for branchs in branch %}
<option value="{{ branchs.pk }}">{{ branchs.name }}</option>
{% endfor %}

bp/task/taskproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Login</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-finance-business.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link href="{% static 'register1.css' %}" rel="stylesheet">
</head>
<body style="background-image: url({% static 'images/hero_2.jpg' %})">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Banking Solutions</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bankapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bankapp:register' %}">Register</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'bankapp:login' %}">Login</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branches
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a>

        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">

<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    </form>
  </div>
</nav>

<br><br><br><br><br>

<form action="login" method="post">
    {% csrf_token %}
    <div class="container">
    <h1>Login Here</h1>

    <hr>

    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" id="username" required><br>

    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" id="password" required><br>

    <hr>


    <button type="submit" class="registerbtn">Submit</button>
        <center><label><b>New User</b></label>
            <a  class="submit-btn" href="{% url 'bankapp:register' %}">Register</a>
        </center>
    </div>
</form>

{% for msg in messages %}
 <h2>{{msg}}</h2>
{% endfor %}


 <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-3 footer-item">
            <h4>Banking Solutions</h4>
            <p>We always aim at providing superior, proactive banking service to niche market globally, while providing cost effective and responsive services</p>
            <ul class="social-icons">
              <li><a rel="nofollow" href="https://fb.com/templatemo" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item">
            <h4>Useful Links</h4>
            <ul class="menu-list">
              <li><a href="#">Intrest Rate</a></li>
              <li><a href="#">Service Charge</a></li>
              <li><a href="#">Policies & Guidelines</a></li>
              <li><a href="#">Doorstep banking</a></li>
              <li><a href="#">Smart Banking</a></li>
              <li><a href="#">Safe Banking</a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item">
            <h4>Additional Pages</h4>
            <ul class="menu-list">
              <li><a href="#">About Us</a></li>
              <li><a href="#">How We Work</a></li>
              <li><a href="#">Quick Support</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
          </div>
          <div class="col-md-3 footer-item last-item">
            <h4>Contact Us</h4>
            <div class="contact-form">
              <form id="contact footer-contact" action="" method="post">
                <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="email" type="text" class="form-control" id="email" pattern="[^ @]*@[^ @]*" placeholder="E-Mail Address" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>Copyright &copy; 2020 Banking Solutions.

            </p>
          </div>
        </div>
      </div>
    </div>

     <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

<!--    <script language = "text/Javascript">-->
<!--      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field-->
<!--      function clearField(t){                   //declaring the array outside of the-->
<!--      if(! cleared[t.id]){                      // function makes it static and global-->
<!--          cleared[t.id] = 1;  // you could use true and false, but that's more typing-->
<!--          t.value='';         // with more chance of typos-->
<!--          t.style.color='#fff';-->
<!--          }-->
<!--      }-->
<!--    </script>-->



</body>
</html>